using System.IO;
using PdfSharpCore.Drawing;
using UglyToad.PdfPig.Core;



namespace PdfProcessor.Services
{
    public class PdfHighlightService
    {
        private readonly PdfRegionService _regionService = new PdfRegionService();
        public void HighlightPdfRegions(string inputPdfPath, string outputFolder)
        {
            string outputPdfPath = Path.Combine(outputFolder, "HighlightedPDF.pdf");

            // Open the existing PDF document for editing
            using (PdfSharpCore.Pdf.PdfDocument document = PdfSharpCore.Pdf.IO.PdfReader.Open(inputPdfPath, PdfSharpCore.Pdf.IO.PdfDocumentOpenMode.Modify))
            {
                foreach (PdfSharpCore.Pdf.PdfPage page in document.Pages)
                {
                    XGraphics gfx = XGraphics.FromPdfPage(page);
                    
                    double pageWidth = page.Width;
                    double pageHeight = page.Height;
                    int pageRotation = (int)page.Rotate;
                    
                    // Define different regions using PDFpig
                    PdfRectangle headerRegion = _regionService.GetHeaderRegion(pageWidth, pageHeight);
                    PdfRectangle footerRegion = _regionService.GetFooterRegion(pageWidth, pageHeight);
                    PdfRectangle fullPageRegion = _regionService.GetFullPageRegion(pageWidth, pageHeight);
                    PdfRectangle bowRegion = _regionService.GetBowRegion(pageWidth, pageHeight, pageRotation);
                    
                    

                    // Draw the yellow highlight
                    XSolidBrush highlightBrush = new XSolidBrush(XColor.FromArgb(150, 255, 255, 0));
                    XRect xRect = PdfRectangleToXRect(bowRegion, pageHeight);
                    gfx.DrawRectangle(highlightBrush, xRect);
                }

                document.Save(outputPdfPath);
            }

            Console.WriteLine($"Highlighted PDF saved at: {outputPdfPath}");
        }
        
        // Convert PDF rectangle generated by PDFpig to Xrect used by PDFSharp
        static XRect PdfRectangleToXRect(PdfRectangle pdfRect, double pageHeight)
        {
            double x = pdfRect.BottomLeft.X;
            double y = pageHeight - pdfRect.TopRight.Y;
            double width = pdfRect.Width;
            double height = pdfRect.Height;

            return new XRect(x, y, width, height);
        }
    }
}